--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4 (Debian 17.4-1.pgdg120+2)
-- Dumped by pg_dump version 17.4 (Debian 17.4-1.pgdg120+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cardapio_item; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cardapio_item (
    id bigint NOT NULL,
    descricao character varying(255),
    preco double precision NOT NULL
);


ALTER TABLE public.cardapio_item OWNER TO postgres;

--
-- Name: cardapio_item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cardapio_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cardapio_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pedido; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pedido (
    id bigint NOT NULL,
    atendido boolean NOT NULL,
    mesa integer NOT NULL
);


ALTER TABLE public.pedido OWNER TO postgres;

--
-- Name: pedido_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pedido ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pedido_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pedido_item; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pedido_item (
    id bigint NOT NULL,
    quantidade integer NOT NULL,
    cardapio_item_id bigint,
    pedido_id bigint
);


ALTER TABLE public.pedido_item OWNER TO postgres;

--
-- Name: pedido_item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pedido_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pedido_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: cardapio_item; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cardapio_item (id, descricao, preco) FROM stdin;
1	Feijão	10
2	Arroz	12
3	Macarrão	20
4	Carne	24
5	Frango	23
6	Açaí	3
7	Sorvete	3
8	Picolé	2
9	Coca-Cola	8
10	Cerveja	10
\.


--
-- Data for Name: pedido; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.pedido (id, atendido, mesa) FROM stdin;
\.


--
-- Data for Name: pedido_item; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.pedido_item (id, quantidade, cardapio_item_id, pedido_id) FROM stdin;
\.


--
-- Name: cardapio_item_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cardapio_item_id_seq', 10, true);


--
-- Name: pedido_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pedido_id_seq', 1, false);


--
-- Name: pedido_item_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pedido_item_id_seq', 1, false);


--
-- Name: cardapio_item cardapio_item_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cardapio_item
    ADD CONSTRAINT cardapio_item_pkey PRIMARY KEY (id);


--
-- Name: pedido_item pedido_item_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pedido_item
    ADD CONSTRAINT pedido_item_pkey PRIMARY KEY (id);


--
-- Name: pedido pedido_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pedido
    ADD CONSTRAINT pedido_pkey PRIMARY KEY (id);


--
-- Name: pedido_item fk5ouo7lg2lg0jwifd1kiej1hax; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pedido_item
    ADD CONSTRAINT fk5ouo7lg2lg0jwifd1kiej1hax FOREIGN KEY (cardapio_item_id) REFERENCES public.cardapio_item(id);


--
-- Name: pedido_item fkeyouxfvoi291lpo5168e6wpej; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pedido_item
    ADD CONSTRAINT fkeyouxfvoi291lpo5168e6wpej FOREIGN KEY (pedido_id) REFERENCES public.pedido(id);


--
-- PostgreSQL database dump complete
--

