
services:
  postgresql:
    image: postgres:17
    container_name: sisrest-db
    restart: always
    environment:
      - POSTGRES_DB=sisrest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  postgresql-data:
    driver: local  