
drop table if exists pedido_item;
drop table if exists pedido;
drop table if exists cardapio_item;

create table cardapio_item (
    id int generated by default as identity ( start with 1, increment by 1 ),
    descricao varchar( 256 ) not null,
    preco double not null,
    primary key( id )
);

create table pedido (
    id int generated by default as identity ( start with 1, increment by 1 ),
    mesa int not null,
    atendido boolean not null,
    primary key( id )
);

create table pedido_item (
    id int generated by default as identity ( start with 1, increment by 1 ),
    cardapio_item_id int not null,
    pedido_id int not null,
    quantidade int not null,
    primary key( id ),
    foreign key ( pedido_id ) references pedido( id ),
    foreign key ( cardapio_item_id ) references cardapio_item( id )
);